version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/app"
    ports:
      - "9999:9999"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

