version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - "./server:/app"
    ports:
      - "9999:9999"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - internal
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:4-bionic
    # image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nonalcholic
    volumes:
      - mongo-volume:/data/db
    networks:
      - internal
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongo
    # restart: always
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: nonalcholic
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: nonalcholic

networks:
  internal:
    driver: bridge

volumes:
  mongo-volume:
    driver: local
